export const SECTIONS = [
  {
    id: 'love',
    label: 'What You Love',
    icon: '♡',
    color: '#E8A87C',
    description: 'Activities and moments that ignite your soul',
    questions: [
      { id: 'love_1', text: 'When do you completely lose track of time? Describe the last few moments this happened.' },
      { id: 'love_2', text: 'If you had a completely free month — no obligations, unlimited budget — how would you actually spend it?' },
      { id: 'love_3', text: 'What topics or problems do you find yourself reading about even when no one asks you to?' },
      { id: 'love_4', text: 'Looking back across Singapore, Shanghai, Korea, Japan, Paris — which chapter felt most alive? What made it so?' },
    ],
  },
  {
    id: 'good',
    label: "What You're Good At",
    icon: '◈',
    color: '#7CB9E8',
    description: 'Your hard-won strengths and rare capabilities',
    questions: [
      { id: 'good_1', text: "What do colleagues and boards consistently say only you can do? What's your irreplaceable contribution?" },
      { id: 'good_2', text: 'Beyond your PhD and Six Sigma expertise, what leadership capabilities feel most distinctly yours?' },
      { id: 'good_3', text: 'Think of a crisis you navigated brilliantly (2008, COVID, Sendai). What did you do that others could not?' },
      { id: 'good_4', text: 'What skills or knowledge do you have that most people in your peer group lack entirely?' },
    ],
  },
  {
    id: 'world',
    label: 'What the World Needs',
    icon: '⊕',
    color: '#87C9A0',
    description: 'The problems and gaps you are positioned to solve',
    questions: [
      { id: 'world_1', text: 'What large-scale problem keeps you up at night — something you believe needs solving in the next decade?' },
      { id: 'world_2', text: 'In energy transition or semiconductors — where do you see the biggest leadership gap you could fill?' },
      { id: 'world_3', text: 'What would you want written about your contribution 20 years from now?' },
      { id: 'world_4', text: 'Is there a country, community, or sector you feel a strong pull to serve or build in?' },
    ],
  },
  {
    id: 'paid',
    label: 'What You Can Be Paid For',
    icon: '◎',
    color: '#C9A0DC',
    description: 'Your market value and economic possibilities',
    questions: [
      { id: 'paid_1', text: 'Beyond employment, what models are you open to — board roles, advisory, venture, academia, entrepreneurship?' },
      { id: 'paid_2', text: "What is your honest relationship with money at this stage? What is 'enough'?" },
      { id: 'paid_3', text: 'What would organisations or funds pay a premium for from someone with your exact background?' },
      { id: 'paid_4', text: 'Where does your APAC and Europe network give you an outsized advantage over any competitor?' },
    ],
  },
  {
    id: 'odyssey',
    label: 'Odyssey Plans',
    icon: '↝',
    color: '#E8D87C',
    description: 'Three radically different 5-year visions',
    questions: [
      { id: 'ody_1', text: 'PLAN A — The Obvious Path: CEO of a comparable enterprise. What does your life look like in 5 years? Be honest about appeal and doubts.' },
      { id: 'ody_2', text: 'PLAN B — The Pivot: If your current path vanished tomorrow, what would you do? What has been quietly waiting?' },
      { id: 'ody_3', text: 'PLAN C — The Wild Card: If money and reputation were irrelevant — what life would you build?' },
      { id: 'ody_4', text: 'Across all three plans — what is the common thread? What must be present in any path?' },
    ],
  },
  {
    id: 'energy',
    label: 'Energy and Values',
    icon: '⚡',
    color: '#E87C7C',
    description: 'What charges and drains you',
    questions: [
      { id: 'energy_1', text: 'Describe a recent week that felt genuinely energising. What were you doing and who were you with?' },
      { id: 'energy_2', text: 'What aspects of your current role quietly drain you? What would you eliminate first?' },
      { id: 'energy_3', text: 'Rank what matters most: Independence / Deep Impact / High Income / Creative Expression / Security / Adventure. Explain your top 3.' },
      { id: 'energy_4', text: 'Where in the world do you actually want to be based? How much travel versus rootedness do you want?' },
    ],
  },
  {
    id: 'wheel',
    label: 'Wheel of Life',
    icon: '◉',
    color: '#7CE8C9',
    description: 'Honest ratings of your life domains today (1-10)',
    sliders: [
      { id: 'wl_career', label: 'Career Fulfilment' },
      { id: 'wl_health', label: 'Health and Vitality' },
      { id: 'wl_family', label: 'Family and Relationships' },
      { id: 'wl_finance', label: 'Financial Wellbeing' },
      { id: 'wl_social', label: 'Social and Community' },
      { id: 'wl_growth', label: 'Personal Growth' },
      { id: 'wl_fun', label: 'Fun, Joy and Adventure' },
      { id: 'wl_spirit', label: 'Meaning and Purpose' },
    ],
  },
  {
    id: 'constraints',
    label: 'Constraints and Commitments',
    icon: '⊗',
    color: '#A0A8B0',
    description: 'Real-world anchors that shape what is possible',
    questions: [
      { id: 'con_1', text: 'What are your genuine non-negotiables — family, health, lifestyle anchors any future must honour?' },
      { id: 'con_2', text: 'How does your partner factor in? Are decisions made jointly and what does she want for your shared life?' },
      { id: 'con_3', text: 'What is your honest timeline? Ready to move now, in 1 year, or after Air Liquide?' },
      { id: 'con_4', text: 'Is there anything you have never said out loud about your next chapter — a fear, a secret wish, or a hard truth?' },
    ],
  },
]

export const WHEEL_SECTION = SECTIONS.find(s => s.id === 'wheel')
